"""Hypothesis engine — generates and evaluates hypotheses.

Hypotheses are generated by strategies (attack planners plug into here).
A failed attack is never discarded: it updates the hypothesis status and
drives the generation of the next hypothesis.
"""

from __future__ import annotations

from openmodels.models import (
    Experiment,
    Hypothesis,
    HypothesisStatus,
    TestOutcome,
)
from openmodels.knowledge.store import KnowledgeStore


class HypothesisEngine:
    """Manages hypothesis lifecycle."""

    def __init__(self, store: KnowledgeStore) -> None:
        self._store = store

    def save(self, hypothesis: Hypothesis) -> None:
        self._store.save_hypothesis(hypothesis)

    def evaluate(self, hypothesis: Hypothesis, experiment: Experiment) -> HypothesisStatus:
        """Determine the status of a hypothesis based on experiment outcome.

        A failed attack is valuable information — the hypothesis is marked
        REJECTED (the specific claim was false) but the knowledge is retained.
        """
        outcome = experiment.outcome
        if outcome == TestOutcome.SUCCESS:
            new_status = HypothesisStatus.ACCEPTED
        elif outcome == TestOutcome.FAILURE:
            new_status = HypothesisStatus.REJECTED
        elif outcome == TestOutcome.BLOCKED:
            new_status = HypothesisStatus.REJECTED
        elif outcome == TestOutcome.ERROR:
            new_status = HypothesisStatus.INCONCLUSIVE
        else:
            new_status = HypothesisStatus.INCONCLUSIVE

        self._store.update_hypothesis_status(hypothesis.id, new_status)
        return new_status